[package]
name = "bv-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

uuid = { version = "1.5.0", features = ["v4", "v7", "fast-rng", "macro-diagnostics", "serde"]}
chrono = { version = "^0.4", features = [ "serde"]}
axum = {version = "0.6.20", default-features = true , features = ["headers", "macros"]}
axum-macros = "0.3.8"
axum-typed-websockets = "0.5.0"

tower-http = { version = "0.4.4", features = ["full"]}
tower = { version = "0.4", features = ["full"] }
bcrypt = "0.15.0"
tokio = { version = "1.33.0", features = ["full"] }
tokio-stream = { version = "0.1.17" }
iprange = { version = "0.6.7", features = ["serde"] }
ipnet = { version = "2.9.0", features = ["serde"] }
textnonce = {version = "1.0.0" }
futures = { version = "0.3.30" }
test-log = { version = "0.2.16", features = ["trace"] }
bimap = { version = "0.6.3" }
md5 = { version = "0.7.0" }
base64 = { version = "0.22.1" }
rand = { version = "0.9.2" }
http = { version = "*" }

thiserror = { version = "2.0.17" }
anyhow = { version = "1.0" }

oauth2 = { version = "4.4.2" }
uuid-mc = { version = "0.3.0" }

chbs = { version = "0.1.1" }
reqwest = { version = "0.11", default-features = false , features = ["json", "rustls-tls"]}
async-trait = { version = "*" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
sqlx = { version = "0.7", features = [ "runtime-tokio", "sqlite", "macros", "json", "uuid", "ipnetwork", "chrono", "migrate" ] }

serenity =  { version = "0.12", default-features = false, features = ["http", "client", "rustls_backend", "builder", "gateway"] }
poise = {version = "0.6.1"}
flate2 = "^1.0.28"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"


[lints]
workspace = true
